version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Catalogos_db
      - POSTGRES_USER=felippe
      - POSTGRES_PASSWORD=felippe
    ports:
      - 5432:5432
volumes:
  postgres-db: